name: Update Exchange Rates

on:
  schedule:
    # 每小时运行一次 (UTC时间)
    - cron: '0 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-rates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run currency crawler
      run: |
        cd currency_ex_rate_sqllite
        python -c "from currency_crawler import CurrencyExchangeRateCrawler; crawler = CurrencyExchangeRateCrawler(); crawler.run_once()"
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add currency_ex_rate_sqllite/data/currency_rates.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update exchange rates [skip ci]" && git push) 